version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: express-server
    ports:
      - "8001:8080"
  environment:
      - MONGO_URL=mongodb://mongo:27017/numer
  depends_on:
      - mongo

  client:
    build: ./client
    container_name: react-client
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  mongo_data: